// src/renderer/components/Head.vue
<template>
  <div class="head">
    <span @click="close" class="no-drag cursor-pointer">x</span>
  </div>
</template>

<script lang="ts">
import {defineComponent} from 'vue';
import {ipcRenderer} from "electron";
import Tool from '../lib/tool';

export default defineComponent({
  name: 'Head',
  methods: {
    close() {
      if (Tool.isNull(this.$Args)) ipcRenderer.send("closed");
      else ipcRenderer.send("dialog-closed", this.$Args.id);
    }
  }
});
</script>

<style lang="scss">
.head {
  position: absolute;
  top: 5px;
  right: 5px;

  span {
    margin-left: 4px;
  }
}

</style>

// src/views/components/Head.svelte
<script>
    import {ipcRenderer} from 'electron';
    import {location, querystring} from 'svelte-spa-router';
</script>

<div class="head">
    <div class="title">
        {$location} - {$querystring}
    </div>
    <div>
        <i on:click={()=>ipcRenderer.send('closed')} class="cuIcon-close no-drag cursor-pointer"></i>
    </div>
</div>

<style lang="scss">
  .head {
    height: 40px;
    padding: 0 10px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 20px;

    .title{
      margin-left: 20px;
    }
    
  }
</style>
